[workspace]
members = ["crates/cli", "crates/tui-app", "crates/web", "crates/backend"]
default-members = ["crates/cli", "crates/tui-app", "crates/backend"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
alloy-primitives = { version = "1.4", default-features = false }
ansi-to-tui = "8.0.0"
clap = { version = "4.5.53", features = ["derive", "env"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
eyre = "0.6.12"
ratatui = { version = "0.30.0", default-features = false, features = [
  "layout-cache",
] }
revm-inspectors = { version = "0.33.2" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.147"
ratzilla = "0.2.0"
futures = "0.3.31"

# Workspace member crates
tui-app = { path = "crates/tui-app" }
web-time = { version = "1.1.0" }
log = "0.4.29"
simplelog = "0.12.2"
# [patch.'https://github.com/foundry-rs/foundry']
# foundry-evm-traces = { path = "../foundry/crates/evm/traces" }
#
# [patch.'https://github.com/paradigmxyz/revm-inspectors']
# revm-inspectors = { path = "../open-source/revm-inspectors" }
#
[patch.crates-io]
# revm-inspectors = { path = "../open-source/revm-inspectors" }
ratzilla = { git = "https://github.com/0xferrous/ratzilla", branch = "merged-branches" }
ratatui = { git = "https://github.com/ratatui/ratatui" }
# ratzilla = { path = "../open-source/ratzilla/" }
beamterm-renderer = { git = "https://github.com/junkdog/beamterm", branch = "main" }
