[package]
name = "traces-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy-primitives = "1.4"
ansi-to-tui = "8.0.0"
clap = { version = "4.5.53", features = ["derive"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
eyre = "0.6.12"
ratatui = "0.30.0"
rayon = "1.11.0"
revm = "33.0.0"
revm-inspectors = { version = "0.33.2" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.147"

# [patch.'https://github.com/foundry-rs/foundry']
# foundry-evm-traces = { path = "../foundry/crates/evm/traces" }
#
# [patch.'https://github.com/paradigmxyz/revm-inspectors']
# revm-inspectors = { path = "../open-source/revm-inspectors" }
#
# [patch.crates-io]
# revm-inspectors = { path = "../open-source/revm-inspectors" }
