[package]
name = "traces-cli"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
color-eyre.workspace = true
eyre.workspace = true
ratatui.workspace = true
revm-inspectors.workspace = true
serde.workspace = true
serde_json.workspace = true
tui-app.workspace = true
