[package]
name = "tui-web"
version.workspace = true
edition.workspace = true

[dependencies]
eyre.workspace = true
ratzilla.workspace = true
tui-app = { workspace = true, features = ["ratzilla"] }
getrandom = { version = "0.3", features = ["wasm_js"] }
getrandom_v2 = { package = "getrandom", version = "0.2.16", features = ["js"] }
revm-inspectors.workspace = true
serde.workspace = true
serde_json.workspace = true
web-sys = { version = "0.3.83", features = [
  "console",
  "Window",
  "Document",
  "FontFaceSet",
  "FontFaceSetIterator",
  "FontFaceSetIteratorResult",
] }
wasm-bindgen = "0.2.106"
wasm-bindgen-futures = "0.4.56"
js-sys = "0.3.83"
web-time.workspace = true
futures.workspace = true
console_error_panic_hook = "0.1.7"

multi_backend = { package = "examples-shared", git = "https://github.com/0xferrous/ratzilla", branch = "merged-branches", subdir = "examples/shared" }
